### PR TITLE
Media Picker: Inserting Images

### PR DESCRIPTION
**Pull request by jleandroperez**
Sergio, mind taking a look at this one?. Media Picker + Image Insertion.

Needs Review: @SergioEstevao
cc @diegoreymendez

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@lantean Code looks good but two things:

 - You didn't need to use PHImageManager for this demo you could grab the UIImage directly from the picker result.
 - After inserting image could the editor be kept in focus and cursor be positioned after the image? Maybe you plan to address this issue on a next PR?

**Comment by jleandroperez** [comment]
@SergioEstevao Nuked `PHPImageManager` usage + re-focusing the editor after the insert.

Ready for another round!. I'll be working on the Layout logic in another PR (this one just embeds the image inline).

Thanks in advance!!

**Comment by SergioEstevao** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thank you sir!

**Pull request merged**
