### PR TITLE
Aztec: Format Bar

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're matching Android's Format Bar behavior:

     **[ Scrollable Items ]** < **[ Fixed Items]**

We'll be adding new Format Bar actions in (upcoming) issues. Few notes:

- **Aztec.FormatBar** no longer inherits from **UIToolbar**.
- **Aztec.FormatBarItem** no longer inherits from **UIBarButtonItem**

Needs Review: @diegoreymendez @SergioEstevao 
Thanks in advance gentlemen!!

### Testing:
1. Launch Aztec on an iPhone SE device
2. Verify that the format bar animates, as soon as it becomes visible
3. Verify that the "Scrollable Items" work as expected
4. Rotate the device and verify everything looks right

Re-test on an iPhone 7 // 7 Plus // iPad (Multitasking). Note that whenever the horizontal sizeClass is regular (7 Plus in landscape, iPad fullscreen), the "Scrollable Items" spacing should be higher.

### Screenshots:
simulator screen shot mar 10 2017 4 38 38 pm

simulator screen shot mar 10 2017 4 44 07 pm

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@jleandroperez two questions:

 - Is it possible to make the toolbar non-scrollable when no scroll is needed? Think iPad in the large size
 - Can we keep the grouping of buttons on the iPad?

**Comment by jleandroperez** [comment]
@SergioEstevao  the scrollView now should get locked whenever there's no overflow. As per the Grouping of Buttons, screenshots below (the code for this one is not pushed).

I'm not quite convinced by the way `iPad Portrait` looks like. Thoughts?

cc @diegoreymendez 

### iPad Landscape Fullscreen:
simulator screen shot mar 13 2017 10 41 09 am

### iPad Slide Over
screen shot 2017-03-13 at 10 41 33 am

### iPad 50%
screen shot 2017-03-13 at 10 41 43 am

### iPhone SE Landscape
simulator screen shot mar 13 2017 10 42 20 am

**Comment by jleandroperez** [comment]
For the record, this is how iPad Portrait looks like (without the patch!):

simulator screen shot mar 13 2017 10 48 13 am

**Comment by jleandroperez** [comment]
**Update Mark III:*
Android is not stretching the buttons. Screenshot below!!

screen shot 2017-03-13 at 10 50 06 am

**Comment by SergioEstevao** [comment]
Really like that the scrolling is locked when you don't need it.

For the majority of scenarios this is working ok, except for this one:

- Start the demo app on the iPad
- Start a multitasking mode and pull an app in.
- tap on the demo editor and check scrolling.
- make the new app started, full screen
- pull the Aztec demo in, just taking the smaller left part of the screen
- check that the scrollbar is not active.

screen shot 2017-03-13 at 23 04 30

**Comment by jleandroperez** [comment]
@SergioEstevao nice catch!! ready for another look!

Thanks!!

**Comment by jleandroperez** [comment]
Thanks @SergioEstevao !!!

**Pull request merged**
