### PR TITLE
Release 1.19.8

### PR DESCRIPTION
**Pull request by twstokes**
The changes incorporated in the release `1.19.8` are:
- https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1334
- https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1344

### CODE REVIEW

**Comment by twstokes** [comment]
My plan is to merge this once the following PRs are approved:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/4557
- https://github.com/WordPress/gutenberg/pull/38633

I did a smoke test with Mobile Gutenberg pointed to the changes for https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1344 and it didn't appear affected. Running the Gutenberg Mobile demo and adding breakpoints [here](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/0465ffe3af19318aeea06bd4286bdd806a1c26c3/Aztec/Classes/TextKit/TextView.swift#L1108) and [here](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/0465ffe3af19318aeea06bd4286bdd806a1c26c3/Aztec/Classes/TextKit/TextView.swift#L1129) never paused execution when manipulating lists, telling me that Mobile Gutenberg doesn't use this path.

**Comment by twstokes** [comment]
@guarani would you mind taking a look at this release PR when convenient?
- The Gutenberg Mobile headings PRs are now approved [[GB](https://github.com/WordPress/gutenberg/pull/38633)] [[GB Mobile](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4557)]
- [I've done testing](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1350#issuecomment-1035840991) to determine that the changes from https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1344 won't affect Mobile Gutenberg

Thanks! 🙇

**Review by guarani — COMMENTED** [review]
The changes look good and match what I see in https://github.com/wordpress-mobile/AztecEditor-iOS/blob/develop/Documentation/ReleaseProcess.md.

I'm not familiar with the other change that's going into this release, but I presume it's also non-breaking, so can be shipped in a patch version.

I see you've checked the Gutenberg Mobile and Gutenberg demo apps with this change and there were no issues. Do we need to create a WPiOS PR, point it to this branch, and have its CI checks pass to know that WPiOS also works? I'm not sure this is needed though.
BTW even though WPiOS classic editor is powered by Aztec, [classic editor tests are currently disabled ](https://github.com/wordpress-mobile/WordPress-iOS/issues/16218), so I'm not sure CI would be able to catch any regressions anyway.

Should I do any manual testing of this release? Let me know how you want to proceed 🙇‍♂️

**Comment by twstokes** [comment]
> I'm not familiar with the other change that's going into this release, but I presume it's also non-breaking, so can be shipped in a patch version.

Good thought: I think it qualifies for a patch in this case due to being a bugfix.

> Do we need to create a WPiOS PR, point it to this branch, and have its CI checks pass to know that WPiOS also works? I'm not sure this is needed though.

Also a good thought. We'd tested the [Headings bug independently](https://github.com/wordpress-mobile/WordPress-iOS/pull/17844), but I'll cut a branch to test this entire release just to be extra safe.

**Comment by twstokes** [comment]
[I've created a PR in WPiOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/17946) to run CI for this release.

**Review by guarani — APPROVED** [review]
Approving since all looks good here from my perspective. I don't think manual testing is needed to review this and the WPiOS PR buildkite tests appear to be passing.

**Pull request merged**
