### PR TITLE
Base work for copy / paste support.

### PR DESCRIPTION
**Pull request by diegoreymendez**
This PR makes some base changes for copy / paste support.

We're replacing:

```switf
override public func replaceCharactersInRange(range: NSRange, withString str: String)
```

with its NSAttributedString counterpart:

```
override public func replaceCharactersInRange(range: NSRange, withAttributedString attrString: NSAttributedString)
```

We're also adding support in the rich text view for pasting styled text (which still doesn't affect HTML).

**How to test:**
1. Try pasting styled text in the text view and make sure it works (doesn't update the DOM yet).
2. Edit regular text and make sure everything works as expected.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
I'll be adding back the original method in a bit.

**Comment by diegoreymendez** [comment]
I added the method back, so this is ready for another look.

**Comment by SergioEstevao** [comment]
:shipit:

**Comment by diegoreymendez** [comment]
Ty @SergioEstevao!

**Pull request merged**
