### PR TITLE
Replace gridicons with SFSymbols on the Example app

### PR DESCRIPTION
**Pull request by SergioEstevao**
Refs: #1224

This PR replaces the use of Gridicons on the example app with SFSymbols.

This will remove the only third party dependency of this project and will also allow us to remove the use of Carthage on the build system.

| Simulator Screen Shot - iPhone 8 - 2021-01-07 at 14 44 20 |  Simulator Screen Shot - iPhone 8 - 2021-01-07 at 14 44 57 |

Notes:
 - This not changes the minimum version supported by the library, Aztec and WordPressEditor are still supporting iOS 11 and above
 - We are only removing the gridicons on Aztec local Example project, the main app will continue to use Gridicons for the legacy editor
 
To test:
 - Check if the project builds correctly locally.
 - Check if the Example app runs and you can use the toolbar to edit
 - Check the overlays on the image using the Image Overlay sample content.

### CODE REVIEW

**Review by loremattei — APPROVED** [review]
This looks good to me and I like that we can simplify the build system removing Carthage. 

✅ Check if the project builds correctly locally.
✅ Check if the Example app runs and you can use the toolbar to edit
✅ Check the overlays on the image using the Image Overlay sample content.

I noticed that there's a Warning when building the Example app because of the switch to iOS 13: 
`AztecEditor-iOS/Example/Example/EditorDemoController.swift:455:22: 'init(input:modifierFlags:action:discoverabilityTitle:)' was deprecated in iOS 13.0`.

Since it's a deprecation notice and it's on the sample app, I'm approving the PR anyway, but I'm reporting it as we may want to fix it in this PR.

**Comment by SergioEstevao** [comment]
> I noticed that there's a Warning when building the Example app because of the switch to iOS 13:
AztecEditor-iOS/Example/Example/EditorDemoController.swift:455:22: 'init(input:modifierFlags:action:discoverabilityTitle:)' was deprecated in iOS 13.0.

Good catch @loremattei , I updated the code to remove that warning and removed some missing references to Carthage.

**Comment by SergioEstevao** [comment]
@ceyhun do you mind giving it a look?

**Review by ceyhun — APPROVED** [review]
Tested with Xcode 12.3 and Example app built fine without Carthage, icons in toolbar and image overlays looking good. The project builds fine as well :shipit:

**Pull request merged**
