### PR TITLE
Paste and Match: Supporting Images

### LINKED ISSUE #172: Paste Behavior
We should allow the host app to define the Paste's Behavior:

- Paste and Match Style
- Paste (and retain the original style)

In both scenarios, the `typingAttributes` should be dropped.

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR adds support for Image Attachments, when running **Paste and Match Style**.
Closes #172

### Testing: Reminders
1. Copy text from Reminders.app
2. Run **Paste and Match Style** in Aztec
3. Verify that the style looks as expected. Compare it with a regular **Paste** OP

### Testing: Safari
1. Copy text from Safari.app. Make sure to include an image asset
2. Run **Paste and Match Style** in Aztec
3. Verify that the style looks as expected. Compare it with a regular **Paste** OP

Needs Review: @diegoreymendez

### CODE REVIEW

**Comment by SergioEstevao** [comment]
I had a look and this is looking good functionality wise. If I have some free time later tonight I can do a full code review.

**Comment by jleandroperez** [comment]
Much appreciated!

**Comment by jleandroperez** [comment]
@diegoreymendez may i bug you with this one?

Thanks ina dvance!

**Comment by jleandroperez** [comment]
Thanks a lot for the review Diego!

**Pull request merged**
