### PR TITLE
Implements bold and italic styles.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Implements bold and italic style editing.  This means you should be able to toggle bold and italics on and off, following the editing logic of our previous editor.

Fixes: #18 and #41.

**Known issues:**
- There's an issue related to our HTML importer not ignoring some characters that can cause node duplication if you switch back and forth several times between visual and HTML mode while editing styles.  This will be fixed separately.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
If you try to select text and select both bold and italic for the text, while it looks correct on the visual editor when I go to the HTML view the resulting markup is wrong. Screenshots here:

screen shot 2016-08-29 at 10 45 37

screen shot 2016-08-29 at 10 45 48



It also looks that after doing the first switch from the visual to the html editor afterward the html editor get stuck in the first conversion.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Good catch.

Fixed the issue you spotted and added a unit test for this specific case.

**Comment by SergioEstevao** [comment]
Good work @diegoreymendez :shipit:

**Comment by diegoreymendez** [comment]
Thanks!

**Comment by diegoreymendez** [comment]
This PR also closed #33

**Pull request merged**
