### PR TITLE
Try/lists

### PR DESCRIPTION
**Pull request by aerych**
Refs #34 

Provides support for formatting and editing ordered and unordered text lists.

The list behavior exists in a few places. 
- `TextList` Simple types providing attribute names, and values for NSAttributedStrings.  I chose to uses classes vs structs initially, but structs might just as well.
- `ListFormatter` Provides various methods for formatting lists and retrieving information about a list.
- `AztecVisualEditor` assigns itself as the UITextViewDelegate in order to mange the cursor when it would overlap/intersect a list marker (bullet or number).  This conflicts with other classes who would implement UITextViewDelegate methods (like the EditorDemoController). The plan here is to proxy UITextViewDelegate calls via `AztecVisualEditorDelegate`.
- `AztecTextStorage` handles cases where a list would be modified by a carriage return or backspace via `public override func replaceCharactersInRange(range: NSRange, withAttributedString attrString: NSAttributedString)`

There are a few things left to be sorted out with the implementation. 
- The selected text range is not quite right after applying a list style.  You can see this by selecting multiple lines and tapping either list button on the format bar.  The selected text will include the previous line. 
- The blockquote style works with paragraph indentation, and as such it is incorrectly highlighting the blockquote button in addition to the list buttons when the cursor intersects a list.  This can be addressed when we update the blockquote style to look for our custom dom attribute.  Out of scope for this feature I think.
- There are issues updating the list for carriage returns and backspacing. The range of the changes is off some where causing text after the list to also be edited, or additional list items to appear or markers to fail to delete.
- Everything needs unit testing.

cc @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@SergioEstevao - @jleandroperez was using this PR to slowly add code for handling lists into Aztec.  I'm not too aware of how much remains to be copied or if that's still valid for our project, but considering you took over, maybe you can evaluate if this can be closed.

Let me know if that's the case or if we still need this to remain open.

**Comment by jleandroperez** [comment]
@diegoreymendez @SergioEstevao as far as i remember, there were few helpful snippets:

- Code to avoid selecting the bullet
- Aaand `TextStorage` (i think!) snippets to deal with newlines

**Comment by SergioEstevao** [comment]
I already did the first... I will have a look on the text storage for the new line methods.

**Comment by SergioEstevao** [comment]
Closing this PR, all the functionality and interesting bit were already ported in the code base.

**Pull request closed without merging**
