### PR TITLE
Reorganize project structure

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR does the following:
- Update the project folder structure to make Example a top level project
- Cleans up and reorganises the Example folder
- Updates to Xcode 8 build settings
- Update project schemas to allow Buddy Build to build and test the project

For buddy build to work project I needed to recreate the project in BuddyBuild console you can have a look here: https://dashboard.buddybuild.com/apps/5811d96b4b29c90100a9441b/build/5811e091bf7ae90100b849ce#tests

Needs Review: @diegoreymendez

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@diegoreymendez managed to make it work with the current buddy build app https://dashboard.buddybuild.com/apps/57ee5274e349f601000457c7?page=1

**Comment by diegoreymendez** [comment]
@SergioEstevao - If you're certain it's ok I recommend removing the extra BuddyBuild project to avoid confusion.

**Comment by diegoreymendez** [comment]
@SergioEstevao - A few notes on the main changes:

> Update the project folder structure to make Example a top level project
> Cleans up and reorganises the Example folder

Why do we want to make the example project top level?

_Remember this is a library repo, not an app repo.  The example app isn't primary._

It's adding tons of files to the root folder that don't really need to be there (ie: the example project file, cartfile, cartfile.resolved, carthage folder).

Is this only to make BuddyBuild be able to run unit tests?

**Comment by SergioEstevao** [comment]
@diegoreymendez  the example project file can be moved down to the example folder. But we need to have the workspace in order to join the two projects and then be able to run the tests on BuddyBuild.

Regarding the Cartage files the Genericons are now a dependency of the library so it makes sense to move it a level up.

**Comment by diegoreymendez** [comment]
>  the example project file can be moved down to the example folder. But we need to have the workspace in order to join the two projects and then be able to run the tests on BuddyBuild.

But the workspace was already at the top level.  Or am I missing something else?

> Regarding the Cartage files the Genericons are now a dependency of the library so it makes sense to move it a level up.

I imagine "Genericons" == "Gridicons".

That's only temporary: one of my upcoming changes is to remove that dependency.  The owner app should define the default icons for this library to use.

In fact if you want me to, I can post a PR for that right away.

More to the point: can we have the BuddyBuild fixes without the folder changes in this PR?

**Comment by SergioEstevao** [comment]
Close this one in favour of this PR: https://github.com/wordpress-mobile/WordPress-Aztec-iOS/pull/134

**Pull request closed without merging**
