### PR TITLE
Issue/1254 blockquote multilevel text color

### LINKED ISSUE #1254: change text color for nested Blockquotes text
**Describe the solution you'd like**
text changes colors in different nest levels like apple mail app

### PR DESCRIPTION
**Pull request by MadeByDouglas**
Fixes #1254 

To test:
changes text color when in quotes or nested quotes for more styling options

logic is now inside `BlockquoteFormatter`

Known issue:
pasting text doesn't change color, would like assistance here.

### CODE REVIEW

**Comment by maxme** [comment]
We recently switched the project license. Aztec is now under the MPL v2.0. More info on this ticket: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1305

If this PR gets merged, the code will be under the MPL v2.0.

**Comment by WestFlow127** [comment]
Can this be merged and released please?

**Comment by WestFlow127** [comment]
This grants support for Dark mode which is imperative for block quotes to appear correctly. I would greatly appreciate if this PR could be merged once the test and licensing is resolved. Thank you in advance.

**Comment by WestFlow127** [comment]
Still waiting...

**Pull request closed without merging**
